### ISSUE TITLE
Background effects do not work in Safari

### ISSUE THREAD

**Issue by tristanratz** [spasimir21/camera-processor#2]
The package does run flawlessly after some work in Chrome, but in Safari as soon as I activate the filters the video gets black and the browser slow. Any ideas on why? Is it a bug or just not possible in Safari at the time

**Comment by spasimir21** [comment]
It seems the issue has something to do with safari not supporting canvas filters/globalCompositeOperation. Unfortunately the only solution seems to be to use a pixel-by-pixel renderer which isn't only complicated but also extremely slow. And even then blurring the background would be entirely out of the picture.

**Comment by tristanratz** [comment]
Thank you for the hint, I'll then add an feature support check and do not show the feature when it's not supported.
